apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MisterHarrow/argogit.git
    targetRevision: HEAD
    path: charts/minecraft
    helm:
      valueFiles:
        - ../../values/minecraft-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
